import React from "react";
import { View, Text } from "react-native";
import LogoLayout from "../../../layout/LogoLayout";

export default () => {
  return (
    <LogoLayout enabled={true} bottomTab={true}>
      <View>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
        <Text>Challenge</Text>
      </View>
    </LogoLayout>
  );
};
